"""create initial tables

Revision ID: 3a345d76fc3f
Revises: 
Create Date: 2026-06-30 19:31:00.114947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3a345d76fc3f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_name'), 'projects', ['name'], unique=False)
    op.create_index(op.f('ix_projects_user_id'), 'projects', ['user_id'], unique=False)
    op.create_table('positionings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('current_step', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('offer', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('uniqueness', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('selected_target_group', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('selected_problem', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('selected_desire', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('selected_transformation', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('selected_positioning', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('selected_big_idea', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('selected_pitch', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('target_group_options', sa.JSON(), nullable=True),
    sa.Column('problem_options', sa.JSON(), nullable=True),
    sa.Column('desire_options', sa.JSON(), nullable=True),
    sa.Column('transformation_options', sa.JSON(), nullable=True),
    sa.Column('positioning_options', sa.JSON(), nullable=True),
    sa.Column('big_idea_options', sa.JSON(), nullable=True),
    sa.Column('pitch_options', sa.JSON(), nullable=True),
    sa.Column('marketing_kit', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_positionings_project_id'), 'positionings', ['project_id'], unique=True)
    op.create_index(op.f('ix_positionings_user_id'), 'positionings', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_positionings_user_id'), table_name='positionings')
    op.drop_index(op.f('ix_positionings_project_id'), table_name='positionings')
    op.drop_table('positionings')
    op.drop_index(op.f('ix_projects_user_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_name'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
