"""drop old string fields

Revision ID: d3570d831266
Revises: d726b66cde84
Create Date: 2026-07-14 17:23:41.036841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3570d831266'
down_revision: Union[str, Sequence[str], None] = 'd726b66cde84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('positionings', 'selected_desire')
    op.drop_column('positionings', 'selected_pitch')
    op.drop_column('positionings', 'selected_big_idea')
    op.drop_column('positionings', 'selected_positioning')
    op.drop_column('positionings', 'selected_problem')
    op.drop_column('positionings', 'selected_transformation')
    op.drop_column('positionings', 'selected_target_group')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('positionings', sa.Column('selected_target_group', sa.VARCHAR(), nullable=True))
    op.add_column('positionings', sa.Column('selected_transformation', sa.VARCHAR(), nullable=True))
    op.add_column('positionings', sa.Column('selected_problem', sa.VARCHAR(), nullable=True))
    op.add_column('positionings', sa.Column('selected_positioning', sa.VARCHAR(), nullable=True))
    op.add_column('positionings', sa.Column('selected_big_idea', sa.VARCHAR(), nullable=True))
    op.add_column('positionings', sa.Column('selected_pitch', sa.VARCHAR(), nullable=True))
    op.add_column('positionings', sa.Column('selected_desire', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
