"""add option selections as JSON

Revision ID: d726b66cde84
Revises: 3a345d76fc3f
Create Date: 2026-07-13 19:52:36.937969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd726b66cde84'
down_revision: Union[str, Sequence[str], None] = '3a345d76fc3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('positionings', sa.Column('selected_options', sa.JSON(), nullable=True))
    op.drop_index(op.f('ix_projects_name'), table_name='projects')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_projects_name'), 'projects', ['name'], unique=False)
    op.drop_column('positionings', 'selected_options')
    # ### end Alembic commands ###
